[package]
name = "ospf-parser"
version = "0.1.0"
authors = ["Pierre Chifflier <chifflier@wzdftpd.net>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
nom = "5.1"
nom-derive = "0.5"
rusticata-macros = "2.0.3"

[dev-dependencies]
hex-literal = "0.2"